// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmzJ_PqFBy2UcVmD81JSyZ8G7a0kth9yE',
    appId: '1:113086635979:web:e1832cb26b985c7087204e',
    messagingSenderId: '113086635979',
    projectId: 'lets-collect-cab16',
    authDomain: 'lets-collect-cab16.firebaseapp.com',
    storageBucket: 'lets-collect-cab16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaF7Ze2tfN-M9A2ywhJPdZozessrKDZh8',
    appId: '1:113086635979:android:59845456b9848a7187204e',
    messagingSenderId: '113086635979',
    projectId: 'lets-collect-cab16',
    storageBucket: 'lets-collect-cab16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBml9iwDvVGUwMNyBF0wFz2D_D-rT-0T5Q',
    appId: '1:113086635979:ios:afc9be36b9afc7be87204e',
    messagingSenderId: '113086635979',
    projectId: 'lets-collect-cab16',
    storageBucket: 'lets-collect-cab16.appspot.com',
    androidClientId: '113086635979-5d8m6p2lh57kjf362rhauorvv2ormks9.apps.googleusercontent.com',
    iosClientId: '113086635979-83usej8u9bl97a44ouj7t7ehlc69nf0e.apps.googleusercontent.com',
    iosBundleId: 'com.crayotech.letsCollect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBml9iwDvVGUwMNyBF0wFz2D_D-rT-0T5Q',
    appId: '1:113086635979:ios:afc9be36b9afc7be87204e',
    messagingSenderId: '113086635979',
    projectId: 'lets-collect-cab16',
    storageBucket: 'lets-collect-cab16.appspot.com',
    androidClientId: '113086635979-5d8m6p2lh57kjf362rhauorvv2ormks9.apps.googleusercontent.com',
    iosClientId: '113086635979-83usej8u9bl97a44ouj7t7ehlc69nf0e.apps.googleusercontent.com',
    iosBundleId: 'com.crayotech.letsCollect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmzJ_PqFBy2UcVmD81JSyZ8G7a0kth9yE',
    appId: '1:113086635979:web:6e33f2acf1ed98f287204e',
    messagingSenderId: '113086635979',
    projectId: 'lets-collect-cab16',
    authDomain: 'lets-collect-cab16.firebaseapp.com',
    storageBucket: 'lets-collect-cab16.appspot.com',
  );
}
